import kandinsky as kd


WHITE = kd.color(255, 255, 255)
BLACK = kd.color(0, 0, 0)

def decode(data):
    override = max(data.count("="), 1)
    data = data.replace("=", "A")
    
    out = 0
    for i in data:
        index = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".index(i)
        out<<=6
        out+=index
    return out.to_bytes(len(data)*6//8, "big")[:-override]
      
def decompress(d):
  r,c="",0
  while c<len(d):
    if d[c]=="°":
      r+=d[c+4]*int(d[c+1:c+4], 16)
      c+=5
    else:
      r+=d[c]
      c+=1
  return r

width = 256
height = 26

line0="°fffA°df5AGAAABgAAAYAAAGAAAB//4Af/+AGABgBgAwAYAMAGAGAAAAg°00aAB4AAD/wAD//AA4f4AcGOAGDhgBgwYAYcGAHODgA/DwAP/4AA/8°011AEAAAHAAAHwAAPwAAPwAAfgAAfgAAfgAA/AAAPAAAC°01eADAAAB4AAAeAAAHgAAAw°026ABgAAAYAAAGAAABgAAAYAAAGAAABg°024ADgAAB+AAA/gAAd4AAGAAABg°016AYAAAGAAABgAAAYAAAGAAA//AAP/wAD/8AABgAAAYAAAGAAABg°015AzAAAMgAAB4AADewAA/8AAAwAAAeAAAMwAADM°01cA/gAB//AA/v4A+APgeAA8OAADjAAAY°01eAMAABjwAB4eAA8D4A8AP/+AA/+AAB8°02bAPwAAD8AAA/°01bAGAAAB3gAAf4AADwPgA+H8AZ7nAGPwwBh4MAYPnAHH/gB/n4APwAAA4°007APgBAH8BwBjA4AYw8AHccAA+eAAHeeAAPfwAPHMAHhjAHgYwBwH8AQA8°00aAHwAAD+BgA7gYAYcHgGH/4B//4D/+GA+BjgBgfwAYD8AHAe°00cAYAADGAAAx+AB//gB//AAcxgAAMYAADH4AP/+AH/4ABzGAAAxgAAM°016A/AAAPw°00bADwAAD8AAA/°028AHP/wBz/8Acf/°060A"
line1="°fffA°df4AMAMAHADgBgAYAYAGAGABgBgAYAcAOAHgHAA+HwAH/4AA/4°00fAfHgAP78AHv/gBh44AYMGAGDBgBgwYAYMGAH//gB//4°00eAcAAAH8AAA/4AAD/wAAz/gAMH4ADAOAAwfgAN/wAD/gAH/AAB+AAAc°008AP/gAP/+ADABgwz8MMP/DDB8wwwwMMMMfDDD/hg4fhwHgD4A//8AD/4°010AD4AAB/AAA94AAMGAHPBwBzwMAcADAAAAw°017AGAAABgAAA8AAAfgAAOcAAHDgADgcAAwDAAcA4ACAE°013ABmAAAZgAAGYAABmAAAZgAAGYAABmAAAZgAAGYAABmAAAZg°013AIAQAHAOAA4HAAHDgABw4AAOcAAB+AAAPAAABg°020APAwAH4eAD+HgBzh4AYAAAG°027AMDAAHh4AB4eAAeHg°020AH/AAD/8AB/PAA5g4AcYGAGGBgBhgYAYYOAGHnABg/wAAHw°00eAB4eAA/PwAf/+AGHhgBhwYAYMGAGHhgBh8YAf38AD8/AAeD°011AOAAAPgAAf4AAfmAAfhgAfgYAfgGAHgBgBgAYAAAGAAABg°00eAfgAAP8GAHjhgBgYYAYGGAGBhgBgY4AcGcAD/+AAf/AAD/°010AcAAAfwYAP8GADDhgBgYYAYGGAGBhgBgYYAYH+AGB/g°00eAGAAABgAAAYAAB//4Af/+AAYDgAGBwABh4AAY4AAG8AAB8AAAeAAAG°00cAOAAAHx4AD+/ABx94AYMGAGDBgBgwYAYMGAGABgBgAw°012AGAAABgfgAYP8AGHngBjgYAZwGAG4BgB8AYAeAMAHAHABg°014A="
line2="°fffA°df3Af/4AP/+AHgAABgAAAYAAAGAAABgAAAYAAAHgAAA//4AH/+°00cAGAAABgAAAYAAAGAAABgB//4Af/+AH//gAAAYAAAGAAABgAAAY°00eAHgAAD+BgA/gYAYcGAGHBgBg4YAYOGAGBzgBgfwAYD8AHAc°00aAEAAABwAAAeD8AD5/AAP44AA+GAADBgAAwYAAMGAH//gB//4°00dAHB/gBh/+AY//wGOAeBnADgfgAYD4AGAOABgBwA4AeA8AD/+AAf/AAA+°00cAH4AAD/AAA54AAcOAAGBgABgYAAYGAAGBgB//4Af/+°00fAf4AAf/gAP/8ADgHgBwAYAYAGAGABgBgAYAcAOADgHAA//gAH/wAAPw°00aAH//gB//4AeAAAD4AAAPgAAAfAAAB8AAAHwAAAeAH//gB//4°009AB/8AAf/+AAf/gAAD4AAH4AAPwAADwAAA/gAAB+AAAH4Af/+AH//gB+°00bABgAAAYAAAGAAABgAAAYAAAGAAABgAAAf/+AH//gB//4°012AGAAgBwAYAeAeADwPAAPHgAB7gAAPwAAA4AAf/+AH//g°017Af/gAf/4AP/+AHABgBgAYAYAGAGABgBgAYAcAG°012ABgAYAYAGAGABgBgAYAf/+AH//gB//4AYAGAGABgBgAY°012AH//gB//4AAMAAADAAAAwAAAMAAADAAAAwAAAMAAH//gB//4°00eAf8MAH/DgBgwYAYMGAGDBgBgAYAYAOAHAHAA8DwAH/4AA/8AABw°010AMGAADBgAAwYAAMGAADBgAAwYAf/+AH//gB//4°016ABgwYAYMGAGDBgBgwYAYMGAGDBgB//4Af/+AH//g°00eAD8AAD/wAB//AA8BwAcAOAGABgBgAYAYAGAGABgBgAYAf/+AH//g°012A=="
line3="°fffA°e16AYAYAfAGAH4/gDuP4AxnOAMZhgDGYYAxmGAMZzgDv/wAf/8AHm°00eADAAAwwAAMMAADDAAAwwAAMcAf/+AH//gAAMAAADAAAAwAAAM°00fAM+AAHPwABjeAAYxgAGMYABjGAAYxgAHM4AA/8AAP+AAA/°00fAB//8Af//AH//wA4GAAcBgAGAYABgGAAYDgAHzwAA/4AAH8°013ABwOAAYBgAGAYABgGAAYBgAHA4AB4cAAP/AAB/°014AD+AAD/wAA4eAAcBgAGAYABgGAAYDgAGBwAB//8Af//°012AB/4AAf/AAH/4AAzOAAYxgAGMYABjGAAZxgAH44AA+MAAH°024AQAAAGAAABwAAAMAAABAAAAQ°008ADAAAAwAAAMAAADAAAAwAAAMAAADAAAAwAAAMAAADAAAAwAAAMAAADAAAAw°00eAQAAAHAAAA8AAAHwAAAeAAABgAAB4AAB4AAB4AAAcAAAE°01bAD///4///+MAABjAAAYwAAGMAABg°015ADAAAA8AAAH4AAAfgAAA/AAAD8AAAPwAAAfgAAB8AAAD°01aADAAAYwAAGMAABjAAAY///+P///g°01aAGADgBgB4AYB+AGA9gBg+YAYeGAGfBgBvAYAfgGAHgBgBwAY°00cAYAAAeAAAfAAAPgAAPgAH/gAB/wAAf/AAAD8AAAPgAAA+AAADgAAAYAAAAAEAAgBwAYAfAeAD4fAAPvAAA/gAAHwAAH+AADz4AD4PAB4B4AcAGAEAAg°006AP+AH//gB/wAAfAAAD+AAAH8AAAfAAAfwAB/AAAeAAAH//gB//4AAA+AAAAgAAB4AAB+AAD/AAH+AAP8AAHwAABwAAAfwAAD/gAAH/AAAP+AAAfgAAA4°00eA=="
line4="°fffA°e07AgAAA4AAB+AAD/AAD+AAD8AAD+AAB/4AA8fwAMB/ADAD4AwAOAM°008ABAAAAYBgAHA4AB4eAAH+AAA/AAAHgAAD8AADzwAB4eAAcBgAEAI°00bAD4AB/+AAf+AAHgAAB+AAAD8AAAPAAAfwAAfgAAHgAAB/+AAH/gAAA4°008AgAAA4AAB+AAB/AAD+AAB8AAAcAAAH4AAAfwAAB/AAAD4AAAO°00fAf/gAH/4AB/+AAMAAAGAAABgAAAYAAAHAAAB/+AAP/g°012ABgGAAYBgAGAYABgGAAYBgAHAYAB//4AP/+AAAYAAAGAAABgAAAY°00bAgAAA+GAAfhgAGcYABjGAAYxgAGOYABh+AAYfAAGDg°014APAAAD4AAAOAAABgAAAYAAAOAAAHAAADwAB/+AAf/g°012A//+AP//gD//4AA4GAAcBgAGAYABgGAAYDgAHzwAA/4AAH8°010A/gAA/8AAOHgAHAYABgGAAYBgAGA4ABgcAP//gD//4°013AH+AAD/wAA4eAAYBgAGAYABgGAAYBgAHA4AB4cAAP/AAB/°00fAB/4AAf/AAH/4AAAGAAABgAAAYAAAOAAAHAAH/4AB/+°00fAf8AAH/4AB/+AAABgAAA4AB/8AAf/gAAA4AAAGAAADAAH/4AB/+°00fAYAAAGAAABgAAAYAAAH//wB//8AYADAGAAwBgAMAYAD°012ABgCAAcBgAHg4AA8cAAHuAAA/AAADgAAAQAAH//wB//8°019AID//nB//5w8AGcMABgDAAYAwAGAMABgDAAYAY°011AYAAAGAAABgAAAYAAAH/5wB/+cAYBnAGAYABgGAAYBg°012AB/4AAf/AAH/4AAAGAAABgAAAYAAAOAAAHAAH//wB//8°016A"
line5="°87bAYAAAOAAAHAAABgAAAYAAAHAAAA4AAAHAAAAwAAAMAAAPAAADgAAAg°00cAYAAAGAAABgAAA8AB///gf+f8OAADjAAAYwAAGMAABg°022AP///7///+////g°022AwAAGMAABjAAAY8AAeH/n/A///gADwAAAYAAAG°014AYAAAGA4ABgeAAYPgAGPYABnmAAbxgAHwYAB4GAAcBg°017A=="

decoded = int.from_bytes(decode(decompress(line6)), "big")
for x in range(width):
   for y in range(height):
      kd.set_pixel(x, y, WHITE if (decoded & (1 << y+x*height)) != 0 else BLACK)
